sudo: required

dist: trusty

addons:
  chrome: stable

language: node_js

node_js:
  - '8'
  - '10'

cache:
  directories:
    - node_modules

branches:
  only:
    - master

notifications:
  email: false

install:
  - npm i

before_script:
  - jdk_switcher use oraclejdk8
  - java -version
  - google-chrome --product-version

script:
  - npm run headless
