trigger:
  - main

pool:
  vmImage: "macOS-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16"
    displayName: "Install Node.js"

  - script: npm install
    displayName: "npm install"

  - script: npm run test
    displayName: "npm test"
