name: ci
on: [push, pull_request]

jobs:
  chromeHeadLess: 
    name: Chrome Headless
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: NPM Install
      uses: actions/npm@master
      args: install
    - name: NPM Test
      uses: actions/npm@master
      args: test
      needs: NPM Install
  